# Generated by Django 5.0.6 on 2024-07-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producttbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cakename', models.CharField(max_length=255)),
                ('cakeprice', models.IntegerField()),
                ('category', models.CharField(choices=[('wedding', 'Wedding cake'), ('anniversary', 'Anniversary cake'), ('birthday', 'Birthday cake'), ('others', 'others')], default='others', max_length=255)),
                ('cakeimage', models.FileField(upload_to='cakes')),
            ],
        ),
    ]
