# Generated by Django 5.0.6 on 2024-07-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sellertbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sellername', models.CharField(max_length=255)),
                ('sellerage', models.IntegerField()),
                ('sellerphone', models.IntegerField()),
                ('selleremail', models.EmailField(max_length=254)),
                ('sellerpassword', models.CharField(max_length=255)),
            ],
        ),
    ]
