# Generated by Django 5.0.6 on 2024-07-22 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerapp', '0001_initial'),
        ('userapp', '0002_carttbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlistbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.customertbl')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sellerapp.producttbl')),
            ],
        ),
    ]
